version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ".:/app"
