version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ".:/app"

  redis:
    image: redis:alpine
    expose:
      - "${REDIS_PORT}"
    restart: always
